### ISSUE TITLE
when using Scrambled Exif, confirm can crash DiCa

### ISSUE THREAD

**Issue by jasoncheng** [jasoncheng/dica#129]
issue can reproduce on my Mi-A2

```
01-10 00:34:55.780  9711  9711 E AndroidRuntime: Process: cool.mixi.dica, PID: 9711
01-10 00:34:55.780  9711  9711 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cool.mixi.dica/cool.mixi.dica.activity.IndexActivity}: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at cool.mixi.dica.activity.IndexActivity.getRealPathFromURI(IndexActivity.kt:218)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at cool.mixi.dica.activity.IndexActivity.processIntent(IndexActivity.kt:194)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at cool.mixi.dica.activity.IndexActivity.onCreate(IndexActivity.kt:133)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
01-10 00:34:55.780  9711  9711 E AndroidRuntime: 	... 11 more
01-10 00:34:55.784  1534  2947 W ActivityManager:   Force finishing activity cool.mixi.dica/.activity.IndexActivity
01-10 00:34:55.786  1534  2947 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
```

**Comment by jasoncheng** [comment]
testing on IG is okay

**Comment by jasoncheng** [comment]
actually, DiCa will remove exif by default (because if copy photo to temp folder without keep exif data)
